BookShopWeb/Areas/Admin/Controllers/BookController.cs
using BookShopWeb.DataAccess.Repository.IRepository;
using BookShopWeb.Models;
using BookShopWeb.Models.ViewModels;
using BookShopWeb.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BookShopWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = Roles.Admin)]
    public class BookController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public BookController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            var books = _unitOfWork.Books.GetAll();
            return View(books);
        }

        public IActionResult Upsert(int? id)
        {
            var bookVM = new BookViewModel
            {
                CategoryList = _unitOfWork.Categories.GetAll()
                    .Select(c => new SelectListItem
                    {
                        Value = c.Id.ToString(),
                        Text = c.Name
                    })
            };

            if (id is null)
            {
                bookVM.Book = new Book
                {
                    BookImages = new List<BookImage>()
                };
                return View(bookVM);
            }
            else
            {
                var book = _unitOfWork.Books.Get(c => c.Id == id, "Category,BookImages");
                if (book is null)
                {
                    return NotFound();
                }

                bookVM.Book = book;
            }

            return View(bookVM);
        }

        [HttpPost]
        public IActionResult Upsert(BookViewModel bookVM)
        {
            bookVM.CategoryList = _unitOfWork.Categories.GetAll()
                .Select(c => new SelectListItem
                {
                    Value = c.Id.ToString(),
                    Text = c.Name
                });

            if (!ModelState.IsValid)
            {
                return View(bookVM);
            }

            if (bookVM.Files is not null)
            {
                var imageUploadResult = UploadImages(bookVM.Files, bookVM.Book);
                if (imageUploadResult.Success)
                {
                    TempData["Success"] = bookVM.Book.Id == 0 ? "Book created successfully" : "Book edited successfully";
                }
                else
                {
                    return BadRequest(imageUploadResult.ErrorMessage);
                }
            }

            bool isNewBook = bookVM.Book.Id == 0;
            if (isNewBook)
            {
                _unitOfWork.Books.Add(bookVM.Book);
            }
            else
            {
                _unitOfWork.Books.Update(bookVM.Book);
            }

            _unitOfWork.Save();

            return RedirectToAction(nameof(Index));
        }

        private ImageUploadResult UploadImages(IEnumerable<IFormFile> files, Book book)
        {
            if (files is null || files.Count() == 0)
            {
                return new ImageUploadResult(false, errorMessage: "No image file provided");
            }

            try
            {
                book.BookImages = new List<BookImage>();
                foreach (var file in files)
                {
                    var directoryUrl = Path.Combine("images", "books", $"book-{book.Id}");
                    var directoryPath = Path.Combine(_webHostEnvironment.WebRootPath, directoryUrl);
                    if (!Directory.Exists(directoryPath))
                    {
                        Directory.CreateDirectory(directoryPath);
                    }

                    var fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    var imageUrl = Path.Combine(directoryUrl, fileName);
                    var imagePath = Path.Combine(_webHostEnvironment.WebRootPath, imageUrl);

                    using (var fs = new FileStream(imagePath, FileMode.Create))
                    {
                        file.CopyTo(fs);
                    }

                    var bookImage = new BookImage
                    {
                        CoverImageUrl = $@"\{imageUrl}",
                        BookId = book.Id,
                    };
                    book.BookImages.Add(bookImage);
                }

                return new ImageUploadResult(true);
            }

            catch (Exception ex)
            {
                return new ImageUploadResult(false, errorMessage: $"Error uploading images: {ex.Message}");
            }
        }

        public void DeleteOldImage(string? imageUrl)
        {
            if (!string.IsNullOrEmpty(imageUrl))
            {
                var imagePath = Path.Combine(_webHostEnvironment.WebRootPath, imageUrl.TrimStart('\\'));
                if (System.IO.File.Exists(imagePath))
                {
                    System.IO.File.Delete(imagePath);
                }
            }
        }

        //public IActionResult Delete(int? id)
        //{
        //    if (id is null)
        //    {
        //        return NotFound();
        //    }

        //    var book = _unitOfWork.Books.Get(c => c.Id == id);
        //    if (book is null)
        //    {
        //        return NotFound();
        //    }

        //    return View(book);
        //}

        //[HttpPost]
        //[ActionName(nameof(Delete))]
        //public IActionResult DeletePOST(int? id)
        //{
        //    if (id is null)
        //    {
        //        return NotFound();
        //    }

        //    var book = _unitOfWork.Books.Get(c => c.Id == id);
        //    if (book is null)
        //    {
        //        return NotFound();
        //    }

        //    DeleteOldImage(book.CoverImageUrl);

        //    _unitOfWork.Books.Remove(book);
        //    _unitOfWork.Save();
        //    TempData["Success"] = "Book deleted successfully";
        //    return RedirectToAction(nameof(Index));
        //}

        // Ajax API Call
        [HttpGet]
        public IActionResult GetAll()
        {
            var products = _unitOfWork.Books.GetAll(navigationProperties: "Category");
            return Json(new { data = products });
        }

        [HttpPost]
        public IActionResult DeleteImage(int id)
        {
            var bookImage = _unitOfWork.BookImages.Get(b => b.Id == id);
            if (bookImage is null)
            {
                return NotFound();
            }

            DeleteOldImage(bookImage.CoverImageUrl);

            _unitOfWork.BookImages.Remove(bookImage);
            _unitOfWork.Save();

            return RedirectToAction(nameof(Upsert), new { id = bookImage.BookId });
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var book = _unitOfWork.Books.Get(b => b.Id == id, "BookImages");
            if (book is null)
            {
                return Json(new { success = false, message = "Error when deleting the book" });
            }

            foreach (var bookImage in book.BookImages)
            {
                DeleteOldImage(bookImage.CoverImageUrl);
            }

            _unitOfWork.Books.Remove(book);
            _unitOfWork.Save();

            return Json(new { success = true, message = $"The book has been deleted" });
        }
    }
}

class ImageUploadResult
{
    public bool Success { get; }

    public string? ErrorMessage { get; }

    public ImageUploadResult(bool success, string? errorMessage = null)
    {
        Success = success;

        ErrorMessage = errorMessage;
    }
}

BookShopWeb/Areas/Admin/Controllers/UserController.cs
using BookShopWeb.DataAccess.Repository.IRepository;
using BookShopWeb.Models;
using BookShopWeb.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BookShopWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class UserController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly UserManager<ApplicationUser> _userManager;

        public UserController(IUnitOfWork unitOfWork, UserManager<ApplicationUser> userManager)
        {
            _unitOfWork = unitOfWork;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPut]
        public IActionResult Block(string id)
        {
            var user = _unitOfWork.Users.Get(b => b.Id == id);
            if (user is null)
            {
                return Json(new { success = false, message = "No user found" });
            }

            if (user.LockoutEnd is null)
            {
                user.LockoutEnd = DateTimeOffset.Now.AddYears(1);
                _unitOfWork.Users.Update(user);
                _unitOfWork.Save();
                return Json(new { success = true, message = $"The user has been blocked" });
            }

            return Json(new { success = false, message = "The user is already blocked" });
        }

        [HttpPut]
        public IActionResult Unblock(string id)
        {
            var user = _unitOfWork.Users.Get(b => b.Id == id);
            if (user is null)
            {
                return Json(new { success = false, message = "No user found" });
            }

            if (user.LockoutEnd is not null)
            {
                user.LockoutEnd = null;
                _unitOfWork.Users.Update(user);
                _unitOfWork.Save();
                return Json(new { success = true, message = $"The user has been unblocked" });
            }

            return Json(new { success = false, message = "The user is already unblocked" });
        }

        [HttpGet]
        public IActionResult GetAll()
        {
            var users = _unitOfWork.Users.GetAll();
            foreach (var user in users)
            {
                var roleId = _unitOfWork.Users.GetRoleId(user.Id);
                var role = _unitOfWork.Users.GetRole(roleId);
                user.Role = role?.Name ?? "No role";
            }
            return Json(new { data = users });
        }

        public IActionResult RoleManagment(string id)
        {
            var user = _unitOfWork.Users.Get(u => u.Id == id);
            if (user is null)
            {
                return NotFound();
            }

            var roleId = _unitOfWork.Users.GetRoleId(user.Id);
            if (roleId is not null)
            {
                var userRole = _unitOfWork.Users.GetRole(roleId);
                user.Role = userRole.Name;
            }

            var userVM = new UserViewModel
            {
                User = user,
                Roles = _unitOfWork.Users.GetRoles().Select(u => new SelectListItem
                {
                    Value = u.Name,
                    Text = u.Name
                }),
            };
            return View(userVM);
        }

        [HttpPost]
        public async Task<IActionResult> RoleManagment(UserViewModel userVM)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var user = await _userManager.FindByIdAsync(userVM.User.Id);
            if (user is null)
            {
                return NotFound();
            }

            user.FullName = userVM.User.FullName;

            var roleId = _unitOfWork.Users.GetRoleId(userVM.User.Id);
            var roleName = _unitOfWork.Users.GetRole(roleId)?.Name;
            if (roleName is not null && roleName != userVM.User.Role)
            {
                await _userManager.RemoveFromRoleAsync(user, roleName);
                await _userManager.AddToRoleAsync(user, userVM.User.Role);

            }

            _unitOfWork.Users.Update(user);
            _unitOfWork.Save();

            return RedirectToAction(nameof(Index));
        }
    }
}

BookShopWeb/Controllers/CategoryController.cs
using BookShopWeb.DataAccess.Repository.IRepository;
using BookShopWeb.Models;
using Microsoft.AspNetCore.Mvc;

namespace BookShopWeb.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CategoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            var categories = _unitOfWork.Categories.GetAll();
            return View(categories);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Category category)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            if (category.Name == category.DisplayOrder.ToString())
            {
                ModelState.AddModelError(string.Empty, "DisplayOrder cannot match Name");
                return View();
            }

            _unitOfWork.Categories.Add(category);
            _unitOfWork.Save();
            TempData["Success"] = "Category was created successfully";
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = _unitOfWork.Categories.Get(c => c.Id == id);
            if (category is null)
            {
                return NotFound();
            }

            return View(category);
        }

        [HttpPost]
        public IActionResult Edit(Category category)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            _unitOfWork.Categories.Update(category);
            _unitOfWork.Save();
            TempData["Success"] = "Category was edited successfully";
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int? id)
        {
            if (id is null)
            {
                return NotFound();
            }

            var category = _unitOfWork.Categories.Get(c => c.Id == id);
            if (category is null)
            {
                return NotFound();
            }

            return View(category);
        }

        [HttpPost]
        [ActionName(nameof(Delete))]
        public IActionResult DeletePOST(int? id)
        {
            if (id is null)
            {
                return NotFound();
            }

            var category = _unitOfWork.Categories.Get(c => c.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            _unitOfWork.Categories.Remove(category);
            _unitOfWork.Save();
            TempData["Success"] = "Category was deleted successfully";
            return RedirectToAction(nameof(Index));
        }
    }
}

BookShopWeb/ViewComponents/ShoppingCartViewComponent.cs
using System.Security.Claims;
using BookShopWeb.DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Mvc;

namespace BookShopWeb.ViewComponents
{
    public class ShoppingCartViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;

        public ShoppingCartViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var userId = UserClaimsPrincipal.FindFirstValue(ClaimTypes.NameIdentifier);
            if (userId is not null)
            {
                var count = HttpContext.Session.GetInt32("ShoppingCart_Count");
                if (count is not null)
                {
                    return View(count.GetValueOrDefault());
                }
                else
                {
                    var cartsCount = _unitOfWork.ShoppingCart.GetAll(c => c.ApplicationUser.Id == userId).Count();
                    HttpContext.Session.SetInt32("ShoppingCart_Count", cartsCount);
                    return View(cartsCount);
                }
            }
            else
            {
                HttpContext.Session.Clear();
                return View(0);
            }
        }
    }
}

BookShopWeb/Views/Shared/_BookDataTables.cshtml
<script src="~/lib/datatables/DataTables-1.13.4/js/jquery.dataTables.min.js"></script>
<script src="~/lib/sweetalert/sweetalert2.min.js"></script>
<script type="text/javascript">
    var dataTable;

    $(function() {
        loadData();
    })

    function loadData() {
        dataTable = $(".table").DataTable({
            ajax: '/admin/book/getall',
            columns: [
                {
                    data: "title",
                    width: "40%"
                },
                {
                    data: "author",
                    width: "15%"
                },
                {
                    data: "listPrice",
                    width: "10%"
                },
                {
                    data: "category.name",
                    width: "15%"
                },
                {
                    data: "id",
                    render: function (data) {
                        return `
                            <div class="d-flex justify-content-between align-items-center">
                                <a href="/Admin/Book/Upsert?id=${data}" class="btn btn-primary">
                                    <i class="bi bi-pencil"></i> Edit
                                </a>
                                <a onClick=deleteBook('/Admin/Book/Delete?id=${data}') class="btn btn-danger">
                                    <i class="bi bi-trash"></i> Delete
                                </a>
                            </div>
                        `
                    },
                    width: "20%"
                }
            ]
        });
    }

    function deleteBook(url) {
        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.isConfirmed) {
                $.ajax({
                    url,
                    type: "DELETE",
                    success: function(data) {
                        dataTable.ajax.reload();
                        toastr.success(data.message);
                    }
                })
            }
        })
    }

</script>

BookShopWeb/Views/Shared/_CompanyDataTables.cshtml
<script src="~/lib/datatables/DataTables-1.13.4/js/jquery.dataTables.min.js"></script>
<script src="~/lib/sweetalert/sweetalert2.min.js"></script>
<script type="text/javascript">
    var dataTable;

    $(function() {
        loadData();
    })

    function loadData() {
        dataTable = $(".table").DataTable({
            ajax: '/admin/company/getall',
            columns: [
                {
                    data: "name",
                    width: "40%"
                },
                {
                    data: "address",
                    width: "15%"
                },
                {
                    data: "country",
                    width: "10%"
                },
                {
                    data: "city",
                    width: "15%"
                },
                {
                    data: "id",
                    render: function (data) {
                        return `
                            <div class="d-flex justify-content-between align-items-center">
                                <a href="/Admin/Company/Upsert?id=${data}" class="btn btn-primary">
                                    <i class="bi bi-pencil"></i> Edit
                                </a>
                                <a onClick=deleteBook('/Admin/Company/Delete?id=${data}') class="btn btn-danger">
                                    <i class="bi bi-trash"></i> Delete
                                </a>
                            </div>
                        `
                    },
                    width: "20%"
                }
            ]
        });
    }

    function deleteBook(url) {
        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.isConfirmed) {
                $.ajax({
                    url,
                    type: "DELETE",
                    success: function(data) {
                        dataTable.ajax.reload();
                        toastr.success(data.message);
                    }
                })
            }
        })
    }
</script>

BookShopWeb/Views/Shared/_DataTables.cshtml
<script src="~/lib/datatables/DataTables-1.13.4/js/jquery.dataTables.min.js"></script>
<script src="~/lib/sweetalert/sweetalert2.min.js"></script>
<script type="text/javascript">
    var dataTable;

    $(function() {
        loadData();
    })

    function loadData() {
        dataTable = $(".table").DataTable({
            ajax: '/admin/book/getall',
            columns: [
                {
                    data: "title",
                    width: "40%"
                },
                {
                    data: "author",
                    width: "15%"
                },
                {
                    data: "listPrice",
                    width: "10%"
                },
                {
                    data: "category.name",
                    width: "15%"
                },
                {
                    data: "id",
                    render: function (data) {
                        return `
                            <div class="d-flex justify-content-between align-items-center">
                                <a href="/Admin/Book/Upsert?id=${data}" class="btn btn-primary">
                                    <i class="bi bi-pencil"></i> Edit
                                </a>
                                <a onClick=deleteBook('/Admin/Book/Delete?id=${data}') class="btn btn-danger">
                                    <i class="bi bi-trash"></i> Delete
                                </a>
                            </div>
                        `
                    },
                    width: "20%"
                }
            ]
        });
    }

    function deleteBook(url) {
        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.isConfirmed) {
                $.ajax({
                    url,
                    type: "DELETE",
                    success: function(data) {
                        dataTable.ajax.reload();
                        toastr.success(data.message);
                    }
                })
            }
        })
    }

</script>

BookShopWeb/Views/Shared/_Layout.cshtml
@inject UserManager<ApplicationUser> UserManager
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookShopWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookShopWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="~/lib/datatables/DataTables-1.13.4/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="~/lib/sweetalert/sweetalert2.min.css"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookShopWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Order" asp-action="Index">Manage Order</a>
                            </li>
                        }
                        @if (User.IsInRole(Roles.Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Dropdown
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="Admin" asp-controller="Category" asp-action="Index">Categories</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="Admin" asp-controller="Book" asp-action="Index">Books</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="Admin" asp-controller="Company" asp-action="Index">Companies</a>
                                    </li>
                                    <li class="dropdown-divider"></li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Create User</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="Admin" asp-controller="User" asp-action="Index">Users</a>
                                    </li>
                                </ul>
                            </li>
                        }
                        @{
                            var userId = UserManager.GetUserId(User);
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Customer" asp-controller="Cart" asp-action="Index" asp-route-userId="@userId">
                                @await Component.InvokeAsync("ShoppingCart")
                            </a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="text-center text-info-emphasis">
            &copy; 2023 - BookShop <i class="bi bi-book"></i> - by Eugene Yukovich
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BookShopWeb/Views/Shared/_Notification.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/toastr/toastr.min.js"></script>
@if (TempData["Success"] != null)
{
    <script type="text/javascript">
        toastr.success("@TempData["Success"]");
    </script>
}
@if (TempData["Error"] != null)
{
    <script type="text/javascript">
        toastr.error("@TempData["Error"]");
    </script>
}

BookShopWeb/Views/Shared/_OrderDataTables.cshtml
<script src="~/lib/datatables/DataTables-1.13.4/js/jquery.dataTables.min.js"></script>
<script type="text/javascript">


    $(function () {
        const queryString = window.location.href;
        const url = new URL(queryString);
        const stat = url.searchParams.get("status");

        loadData(stat);
    })

    function loadData(status) {
        $(".table").DataTable({
            ajax: `/admin/order/getall?status=${status}`,
            columns: [
                {
                    data: "id",
                    width: "5%"
                },
                {
                    data: "fullName",
                    width: "25%"
                },
                {
                    data: "phoneNumber",
                    width: "20%"
                },
                {
                    data: "applicationUser.email",
                    width: "20%"
                },
                {
                    data: "paymentStatus",
                    width: "10%"
                },
                {
                    data: "orderTotal",
                    width: "10%"
                },
                {
                    data: "id",
                    render: function (data) {
                        return `
                            <div class="d-flex justify-content-center align-items-center">
                                <a href="/Admin/Order/Details?id=${data}" class="btn btn-primary">
                                    <i class="bi bi-pencil"></i> Edit
                                </a>
                            </div>
                        `
                    },
                    width: "10%"
                }
            ]
        });
    }
</script>